# Domain bridge to bridge the topics between the drone (contact application) and ground station (operator)
# contact: ROS_DOMAIN_ID:=0
# operator: ROS_DOMAIN_ID:=1
name: domain_bridge_drone_ground_station
topics:

  # contact --> operator
  /idas_orbslam3/features/compressed:
    type: sensor_msgs/msg/CompressedImage
    from_domain: 0
    to_domain: 1
  /camera/infra1/image_rect_raw/compressed:
    type: sensor_msgs/msg/CompressedImage
    from_domain: 0
    to_domain: 1
  /idas/orb/dbg:
    type: std_msgs/msg/String
    from_domain: 0
    to_domain: 1
  /idas_dbg/orb/pose_rate:
    type: std_msgs/msg/Float64
    from_domain: 0
    to_domain: 1
  /out/target_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 1
  /out/odom_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 0
    to_domain: 1
  /fmu/out/vehicle_control_mode:
    type: px4_msgs/msg/VehicleControlMode
    from_domain: 0
    to_domain: 1
  /fmu/out/vehicle_status:
    type: px4_msgs/msg/VehicleStatus
    from_domain: 0
    to_domain: 1
  /out/battery:
    type: std_msgs/msg/Float64
    from_domain: 0
    to_domain: 1
  /contact/dist_controller/info:
    type: idas_ros_msgs/msg/NodeState
    from_domain: 0
    to_domain: 1
  /contact/node_state:
    type: idas_ros_msgs/msg/NodeState
    from_domain: 0
    to_domain: 1
  /contact/info:
    type: std_msgs/msg/String
    from_domain: 0
    to_domain: 1
  /contact/dist_ctrl/wall_dist:
    type: std_msgs/msg/Float64
    from_domain: 0
    to_domain: 1
  /contact/dist_ctrl/curr_dist:
    type: std_msgs/msg/Float64
    from_domain: 0
    to_domain: 1

  # contact <-- operator
  /in/joystick:
    type: idas_ros_msgs/msg/Joystick
    from_domain: 1
    to_domain: 0
  /contact/dist_ctrl/add_dist:
    type: std_msgs/msg/Float64
    from_domain: 1
    to_domain: 0
  /rolling_brush/speed:
    type: std_msgs/msg/Int32
    from_domain: 1
    to_domain: 0
  /in/target_rel:
    type: geometry_msgs/msg/Pose
    from_domain: 1
    to_domain: 0